FROM ubuntu
MAINTAINER Jonathan Stuart Ward <se.jonathan@ccpgames.com>

# Install software
RUN apt-get install -y wget

RUN mkdir /opt/aggregateD
RUN ls /opt
RUN wget  -O /opt/aggregateD/aggregateD https://github.com/ccpgames/aggregateD/releases/download/0.1/aggregateD-linux-x64
RUN ls /opt
EXPOSE 8003

ADD aggregated.yaml /opt/aggregateD/
RUN ls /opt/aggregateD/
RUN chmod -R 700 /opt/aggregateD
ENTRYPOINT /opt/aggregateD/aggregateD -config /opt/aggregateD/aggregated.yaml
